const LOADING_COIN_DATA = ' LOADING_COIN_DATA';
const LOADING_COIN_DATA_SUCCESS = 'LOADING_COIN_DATA_SUCCESS';
const LOADING_COIN_DATA_FAILED = 'LOADING_COIN_DATA_FAILED';

export {
  LOADING_COIN_DATA,
  LOADING_COIN_DATA_SUCCESS,
  LOADING_COIN_DATA_FAILED
};